AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Backup EC2 with the Data Lifecycle Manager
Parameters:
  WorkflowNotifactions:
    Description: "Group of resources that describe the workflow notification stack"
    Type: String
Resources:
  WorkflowStartSuccessFilter:
    Type: AWS::Logs::MetricFilter
    Properties: 
      FilterPattern: "WorkflowManagerActor Successfully started"
      LogGroupName: "cromwell-server"
      MetricTransformations: 
        -
          DefaultValue: "0"
          MetricName: "cromwell-workflow-start-success"
          MetricNamespace: "cromwell"
          MetricValue: "1"

  WorkflowFailedStateFilter:
    Type: AWS::Logs::MetricFilter
    Properties: 
      FilterPattern: "\"is in a terminal state: WorkflowFailedState\""
      LogGroupName: "cromwell-server"
      MetricTransformations: 
        -
          DefaultValue: "0"
          MetricName: "cromwell-workflow-failed"
          MetricNamespace: "cromwell"
          MetricValue: "1"

  WorkflowStartSuccessAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Cromwell server successfully started a workflow"
      AlarmName: "cromwell-server-start-success"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      MetricName: "cromwell-workflow-start-success"
      Namespace: "cromwell"
      Period: 60
      Statistic: "Maximum"
      Threshold: "1.0"
      TreatMissingData: "missing"

  WorkflowNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: "cromwell-server"
      FifoTopic: false